export const productsdata = [
  {
    id: 12354,
    quantity: 1,
    storeProductId: 1764,
    productId: 1,
    pname: "Fresh Tomato",
    pUnit: "1Kg",
    pimage: "http://www.way2door.com/images/products/tamato.jpg",
    price: 60,
    sellPrice: 50,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 2567,
    quantity: 1,
    storeProductId: 1765,
    productId: 2,
    pname: "Potato Old",
    pUnit: "1 Kg",
    pimage: "http://www.way2door.com/images/products/potato.jpg",
    price: 30,
    sellPrice: 20,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 3231,
    quantity: 1,
    storeProductId: 1766,
    productId: 3,
    pname: "Onion",
    pUnit: "1Kg",
    pimage: "http://www.way2door.com/images/products/onion.jpg",
    price: 50,
    sellPrice: 30,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 45345,
    quantity: 1,
    storeProductId: 1774,
    productId: 315,
    pname: "Green Chilli",
    pUnit: "250 gm",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Chilli.jpg",
    price: 20,
    sellPrice: 15,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 53453,
    quantity: 1,
    storeProductId: 1777,
    productId: 8,
    pname: "Garlic (Lehsun)",
    pUnit: "250 gm",
    pimage: "http://www.way2door.com/images/products/garlic_lehsun.jpg",
    price: 60,
    sellPrice: 40,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 634534,
    quantity: 1,
    storeProductId: 1779,
    productId: 334,
    pname: "Green Capsicum ( Shimla Mirch )",
    pUnit: "250 gm",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Capsicum-way2door.jpg",
    price: 40,
    sellPrice: 20,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 75678,
    quantity: 1,
    storeProductId: 1782,
    productId: 327,
    pname: "Carrot",
    pUnit: "1 Kg",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Orange Carrot-way2door.jpg",
    price: 50,
    sellPrice: 40,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 85675,
    quantity: 1,
    storeProductId: 1788,
    productId: 9,
    pname: "Coriander",
    pUnit: "250 gm",
    pimage: "http://www.way2door.com/images/products/coriander.jpg",
    price: 30,
    sellPrice: 10,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 9567,
    quantity: 1,
    storeProductId: 1793,
    productId: 175,
    pname: "Pomegranate (Anaar)",
    pUnit: "1 Kg",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Pomegranate (Anaar).jpg",
    price: 180,
    sellPrice: 155,
    mainCat: "Fresh_Fruits",
  },
  {
    id: 1056,
    quantity: 1,
    storeProductId: 1800,
    productId: 39,
    pname: "Cabbage",
    pUnit: "1 unit",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Cabbage-way2door.jpg",
    price: 35,
    sellPrice: 30,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 11567,
    quantity: 1,
    storeProductId: 1802,
    productId: 66,
    pname: "Cauliflower",
    pUnit: "1 unit",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Cauliflower.jpg",
    price: 50,
    sellPrice: 30,
    mainCat: "Fresh_Vegetables",
  },
  {
    id: 125675,
    quantity: 1,
    storeProductId: 1811,
    productId: 34,
    pname: "Guava ( Amrud )",
    pUnit: "1Kg",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Guava.jpg",
    price: 65,
    sellPrice: 60,
    mainCat: "Fresh_Fruits",
  },
  {
    id: 135674,
    quantity: 1,
    storeProductId: 1816,
    productId: 30,
    pname: "Papaya 1 KG",
    pUnit: "1 unit",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Papaya-way2door.jpg",
    price: 60,
    sellPrice: 55,
    mainCat: "Fresh_Fruits",
  },
  {
    id: 14567,
    quantity: 1,
    storeProductId: 1819,
    productId: 224,
    pname: "Green Coconut",
    pUnit: "1 unit",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Coconut-way@door.jpg",
    price: 50,
    sellPrice: 0,
    mainCat: "Fresh_Fruits",
  },
  {
    id: 15567,
    quantity: 1,
    storeProductId: 2608,
    productId: 229,
    pname: "Banana",
    pUnit: "12 unit",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Yellaki (Kathali Kala) Banana-way@door.jpg",
    price: 60,
    sellPrice: 50,
    mainCat: "Fresh_Fruits",
  },
  {
    id: 16567,
    quantity: 1,
    storeProductId: 2609,
    productId: 25,
    pname: "Kashmiri Apple",
    pUnit: "1 Kg",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Kashmiri Apple-way2door.jpg",
    price: 140,
    sellPrice: 100,
    mainCat: "Fresh_Fruits",
  },
  {
    id: 17453,
    quantity: 1,
    storeProductId: 2610,
    productId: 17145,
    pname: "Shimla Apple",
    pUnit: "1 Kg",
    pimage:
      "http://www.way2door.com/AllProducts/fruits_and_vegetables/Shimla Apple.jpg",
    price: 170,
    sellPrice: 130,
    mainCat: "Fresh_Fruits",
  },
  {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 13710154,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  },
  {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 137198,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 1371335,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 137111,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 137122,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 137133,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 137144,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 137155,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 137199,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 179053,
    quantity: 1,
    storeProductId: 2610,
    productId: 137166,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  }, {
    id: 1790537,
    quantity: 1,
    storeProductId: 2610,
    productId: 137177,
    pname: "Egg",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/s/150502_6-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Fresh_Non_Veg",
  },
  {
    id: 979057873,
    quantity: 1,
    storeProductId: 2610,
    productId: 17519,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },
  {
    id: 979053897,
    quantity: 1,
    storeProductId: 2610,
    productId: 17518,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },  {
    id: 97905398,
    quantity: 1,
    storeProductId: 2610,
    productId: 17517,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },  {
    id: 9790539,
    quantity: 1,
    storeProductId: 2610,
    productId: 17516,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },  {
    id: 9790538,
    quantity: 1,
    storeProductId: 2610,
    productId: 17515,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },  {
    id: 97905368,
    quantity: 1,
    storeProductId: 2610,
    productId: 17514,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },  {
    id: 97905367,
    quantity: 1,
    storeProductId: 2610,
    productId: 17513,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },  {
    id: 9790535,
    quantity: 1,
    storeProductId: 2610,
    productId: 17512,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },  {
    id: 9790534,
    quantity: 1,
    storeProductId: 2610,
    productId: 17511,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },  {
    id: 9790533,
    quantity: 1,
    storeProductId: 2610,
    productId: 1751,
    pname: "Amul Milk",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/70001832_2-amul-taaza-fresh-toned-milk.jpg",
    price: 70,
    sellPrice: 30,
    mainCat: "Dairy_Product",
  },
  {
    id: 9799532,
    quantity: 1,
    storeProductId: 2610,
    productId: 105121,
    pname: "Almond",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/40125916_10-bb-royal-organic-almondbadam.jpg",
    price: 790,
    sellPrice: 530,
    mainCat: "Dry_Fruits",
  },
  
  {
    id: 99953,
    quantity: 1,
    storeProductId: 2610,
    productId: 10951,
    pname: "Almond",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/40125916_10-bb-royal-organic-almondbadam.jpg",
    price: 790,
    sellPrice: 530,
    mainCat: "Dry_Fruits",
  },
  {
    id: 9799953,
    quantity: 1,
    storeProductId: 2610,
    productId: 10651,
    pname: "Almond",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/40125916_10-bb-royal-organic-almondbadam.jpg",
    price: 790,
    sellPrice: 530,
    mainCat: "Dry_Fruits",
  },
  {
    id: 97353,
    quantity: 1,
    storeProductId: 2610,
    productId: 7751,
    pname: "Almond",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/40125916_10-bb-royal-organic-almondbadam.jpg",
    price: 790,
    sellPrice: 530,
    mainCat: "Dry_Fruits",
  },
  {
    id: 979933,
    quantity: 1,
    storeProductId: 2610,
    productId: 1111,
    pname: "Almond",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/40125916_10-bb-royal-organic-almondbadam.jpg",
    price: 790,
    sellPrice: 530,
    mainCat: "Dry_Fruits",
  },
  {
    id: 9797,
    quantity: 1,
    storeProductId: 2610,
    productId: 3351,
    pname: "Almond",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/40125916_10-bb-royal-organic-almondbadam.jpg",
    price: 790,
    sellPrice: 530,
    mainCat: "Dry_Fruits",
  },
  {
    id:995300,
    quantity: 1,
    storeProductId: 2610,
    productId: 105001,
    pname: "Almond",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/40125916_10-bb-royal-organic-almondbadam.jpg",
    price: 790,
    sellPrice: 530,
    mainCat: "Dry_Fruits",
  },
  {
    id: 979543953,
    quantity: 1,
    storeProductId: 2610,
    productId: 103451,
    pname: "Almond",
    pUnit: "1 Kg",
    pimage:
      "https://www.bigbasket.com/media/uploads/p/l/40125916_10-bb-royal-organic-almondbadam.jpg",
    price: 790,
    sellPrice: 530,
    mainCat: "Dry_Fruits",
  },
];
